# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: validate-toml
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-mod-tidy

  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.1
    hooks:
      - id: go-fmt-import
      - id: gofumpt # requires github.com/mvdan/gofumpt
      - id: go-static-check # install https://staticcheck.io/docs/

  # errcheck does not accept argument in the repository above
  - repo: local
    hooks:
      - id: errcheck
        name: go errcheck
        entry: errcheck -ignoretests ./...
        language: system
        types: [shell]
        always_run: true
