name: Pipeline

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v**"
  pull_request:
    branches:
      - main

jobs:
  # Documentation: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: "Pull application code"
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.1"
      - name: Install dependencies
        run: |
          go version
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2
          ls $(go env GOPATH)/bin
      - name: Run vet & lint
        run: |
          go vet .
          $(go env GOPATH)/bin/golangci-lint run

      - name: Run tests
        run: |
          go test ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.codecov_token }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
